version: '3.8'

services:
  # Servidor Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/var/www/html
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - wordpress-network
    restart: unless-stopped

  # PHP-FPM
  php:
    image: wordpress:php8.2-fpm-alpine
    container_name: php-fpm
    volumes:
      - ./www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - wordpress-network
    restart: unless-stopped
    depends_on:
      - mysql

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - wordpress-network
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: wpuser
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 100M
    networks:
      - wordpress-network
    restart: unless-stopped
    depends_on:
      - mysql

  # Certbot para Let's Encrypt
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - wordpress-network

  # Servidor FTP
  ftp:
    image: delfer/alpine-ftp-server
    container_name: ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - ./www:/home/ftpuser/www
    environment:
      USERS: "ftpuser|${FTP_PASSWORD}|/home/ftpuser/www"
      ADDRESS: ${SERVER_IP}
    networks:
      - wordpress-network
    restart: unless-stopped

networks:
  wordpress-network:
    driver: bridge

volumes:
  mysql-data:
